### ISSUE TITLE
Heads Up! Your secret key is exposed.

### ISSUE THREAD

**Issue by OGoodness** [Dmitri-Sintsov/djk-sample#3]
Not sure if this was intended, just popping it. 
But your secret key is exposed here: https://github.com/Dmitri-Sintsov/djk-sample/blob/master/djk_sample/settings.py

**Comment by Dmitri-Sintsov** [comment]
It's just the sample project used to show the features of
django-jinja-knockout and to CI test it. It is not supposed to be hosted
and run at actual Web site, just at localhost.

чт, 11 Июн 2020 г., 22:09 Noah <notifications@github.com>:

**Comment by Dmitri-Sintsov** [comment]
Fixed by f7d529da52cb82ce659ab606fcccba827d439218
