### ISSUE TITLE
Current system as described in the docs does not work. 

### ISSUE THREAD

**Issue by dataforxyz** [Dmitri-Sintsov/djk-sample#6]
Due to you making changes to the system there is a mismatch which causes this error. https://github.com/Dmitri-Sintsov/djk-sample/issues/4. but its only an issue of mismatch versions of djk_ui and django-jinja-knockout.

In short they should both be recomend/suggested stable OR current. Right now recomend in doc is djk_ui stable and django-jinja-knockout current.

This did not work https://github.com/Dmitri-Sintsov/djk-sample/pull/5 as you noted here https://github.com/Dmitri-Sintsov/djk-sample/commit/745c015cf9296998236004aff7794c3af2429d36. 

The other solution is just to recommend usage of the latest of djk_ui instead of the stable. in windows and linux both it says to use the stable. but this code run with this git today wont work. it errors up https://github.com/Dmitri-Sintsov/djk-sample/issues/. 

"To use the current stable Bootstrap 3 version of djk_ui:

python3 -m pip install -U -r requirements/bs3.txt

To use the current stable Bootstrap 4 version of djk_ui:

python3 -m pip install -U -r requirements/bs4.txt"

either by also commenting that they may not work and the latest can be installed using 
https://github.com/Dmitri-Sintsov/djk-sample/blob/master/4bs.cmd or 
https://github.com/Dmitri-Sintsov/djk-sample/blob/master/4bs.sh

or just changing the requirements/bs3.txt version to not include v1.0.0 at the end. as that is the only place its used. and not mentioned in the documentation. 

I know all that is poorly written. I am writing a decent fix for this also.

**Comment by Dmitri-Sintsov** [comment]
For stable version one should install:

    python3 -m pip install requirements.txt

then install either bs3 or bs4 version with:

    python3 -m pip install -U -r requirements/bs3.txt

or

    python3 -m pip install -U -r requirements/bs4.txt"

For current alpha version:

    python3 -m pip install requirements/dev.txt

then:

    ./3bs.sh
or

    ./4bs.sh

I will check the README maybe it requires some corrections.
Lot of documentation has to be updated for v2.0.

**Comment by Dmitri-Sintsov** [comment]
I see the README suggest to use stable versions. It probably should work. Although I currently use 2.0a, which is unreleased on pypi yet.

**Comment by Dmitri-Sintsov** [comment]
However the sample app itself was updated for 2.0a. I probably should release 2.0a faster, however there is lot of work to update the documentation and the related projects.

**Comment by Dmitri-Sintsov** [comment]
For pypi version of django-jinja-knockout please try with:

902a5d3330b0c6e81eb80c0cdceef158329cebdf

as the newer version of djk-sample were updated to use 2.0a version with es modules, which are incompatible to each other.

In Ubuntu Linux issue the following commands:

    python3 -m venv djk-1.x
    cd djk-1.x
    source bin/activate
    git clone https://github.com/Dmitri-Sintsov/djk-sample.git
    cd djk-sample
    git checkout 902a5d3330b0c6e81eb80c0cdceef158329cebdf
    pip3 install -U django-jinja-knockout==1.1.0 git+https://github.com/Dmitri-Sintsov/djk-bootstrap3.git@v1.0.0 Django\<3 django-allauth==0.45 selenium\<4
    mkdir logs
    sudo snap install chromium
    DJK_WEBDRIVER='django_jinja_knockout.webdriver.chromium.webdriver' python3 manage.py test

To return to current development version use:

    git checkout master

**Comment by Dmitri-Sintsov** [comment]
Just released v2.0.0 with updated installation instructions both for stable / dev versions.

https://pypi.org/project/django-jinja-knockout/2.0.0/
